[package]
name = "csv_hash"
version = "0.1.0"
description = "CSV field hashing desktop client"
edition = "2024"

[lib]
name = "csv_hash_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "csv_hash"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.5.2", features = [] }

[dependencies]
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
tauri = { version = "2.9.5", features = [] }
tauri-plugin-dialog = "2.4.1"
